### ISSUE TITLE
Can you explain what PRETRAINED_MODEL used in Fine-tuning is?

### ISSUE THREAD

**Issue by ShepherdX** [facebookresearch/EmpatheticDialogues#15]

**Comment by EricMichaelSmith** [comment]
Hi there,

That's the model file that results from running the pretraining commands at https://github.com/facebookresearch/EmpatheticDialogues#pretraining and https://github.com/facebookresearch/EmpatheticDialogues#pretraining-1 .

**Comment by ShepherdX** [comment]
Thank you for your reply : )
