### ISSUE TITLE
Excuse me, there is somthing I feel confused

### ISSUE THREAD

**Issue by lsy641** [facebookresearch/EmpatheticDialogues#17]
I don't really understand the relationship betwwen hit id and conv id, and can you explain the case in dataset below :
![image](https://user-images.githubusercontent.com/26696711/67869373-4ee03d80-fb68-11e9-8119-7ca6768f9739.png)
I think in hit 1: conv 3, speaker and listener should talk about  "I showed a guy how to run a good bead in welding class and he caught on quick" with "proud" emotion

**Comment by EricMichaelSmith** [comment]
Hi! Here, you can ignore the hit ID: the conv ID tells you what conversation you're looking at. I understand your confusion, though - that particular conversation you mentioned is definitely off-topic given the situation prompt.

**Comment by luchenyao** [comment]
@EricMichaelSmith  thanks a lot, i was also confused just a moment ago...
