### ISSUE TITLE
How do you decide these 32 emotion labels?

### ISSUE THREAD

**Issue by Miopas** [facebookresearch/EmpatheticDialogues#18]
I am kind of confused about where the 32 emotion labels from. Because some emotions are really close to another, I try to find some resources to find the difference between them.  I read all of the references mentioned in the image below but I failed to find all of the 32 emotions in these papers. 
Would you provide some information about this?

![image](https://user-images.githubusercontent.com/10841135/68811642-231c8780-063f-11ea-8a2a-635918fe0f44.png)

**Comment by EricMichaelSmith** [comment]
Hi there! Just talked to my co-authors, who said: "we added the 8 emotion axes from Plutchik (anger, anticipation, joy, trust, fear, surprise, sadness, disgust). 2 of those are not in Ekman's 6: anticipation and trust".

However, we didn't use anticipation and trust directly, but turned these into several adjectives each: (anticipating, anxious, prepared) and (trusting, faithful, confident, sentimental, caring), respectively. Hope this helps!

**Comment by Miopas** [comment]
> Hi there! Just talked to my co-authors, who said: "we added the 8 emotion axes from Plutchik (anger, anticipation, joy, trust, fear, surprise, sadness, disgust). 2 of those are not in Ekman's 6: anticipation and trust".
> 
> However, we didn't use anticipation and trust directly, but turned these into several adjectives each: (anticipating, anxious, prepared) and (trusting, faithful, confident, sentimental, caring), respectively. Hope this helps!

Thanks a lot. It's really helpful. By the way, I guessed that "afraid" and "terrified" labels are from the "fear" label provided in 8 emotion axes from Plutchik. I attached my notes for these 32 emotion labels in case anyone is interested.
![image](https://user-images.githubusercontent.com/10841135/68916353-9273a380-0733-11ea-83a9-d0df9a2737b6.png)

**Comment by Miopas** [comment]
Sorry for that I have more questions about the emotion category design. Why do you turn "anticipation" and "trust" into more emotions labels? Why do you define these fine-grained emotions rather than the basic 6 emotions from Ekman? Does the emotion category design matter for the dialogue generation task?

**Comment by EricMichaelSmith** [comment]
Ah, "anticipation" and "trust" were deemed to be a bit too vague to serve as specific emotions. Regarding why we use the fine-grained emotions at all, my co-author said that "the main goal was to cover a thorough and broad array of emotions that can always be grouped together more coarsely later". Certainly, we find that having fine-grained emotions leads to a good diversity of conversations and conversational moods, which should lead to a model more robust at being empathetic in many types of scenarios.

**Comment by Miopas** [comment]
> Ah, "anticipation" and "trust" were deemed to be a bit too vague to serve as specific emotions. Regarding why we use the fine-grained emotions at all, my co-author said that "the main goal was to cover a thorough and broad array of emotions that can always be grouped together more coarsely later". Certainly, we find that having fine-grained emotions leads to a good diversity of conversations and conversational moods, which should lead to a model more robust at being empathetic in many types of scenarios.

Got it. Thank you very much!!
