### ISSUE TITLE
data file

### ISSUE THREAD

**Issue by yurui12138** [facebookresearch/EmpatheticDialogues#19]
Hello, I recently read your paper. Your work is very meaningful for the dialogue system, so I want to track your work. However, due to my limited technical level, I have some questions about the code and hope to get your advice.
When using your code, how should the files in the data folder mentioned in the parameters be obtained? For example, how does "word dictionary" in "reddit dir" get?

**Comment by EricMichaelSmith** [comment]
Hi there! See my response at https://github.com/facebookresearch/EmpatheticDialogues/issues/16 - that should give you a sense of how to load in Reddit data in the proper format. If you want to use a BERT model, you may also want to take a look at the code in `build_bert_dictionary()` at https://github.com/facebookresearch/EmpatheticDialogues/blob/master/empchat/datasets/loader.py#L48 for how to create a BERT dictionary.

**Comment by yurui12138** [comment]
Thank you very much for your reply!

**Comment by EricMichaelSmith** [comment]
Sure thing - happy to help!
