### ISSUE TITLE
I wonder where you collected so many situations?

### ISSUE THREAD

**Issue by lsy641** [facebookresearch/EmpatheticDialogues#20]
Sorry, maybe a little wiered. I wonder to know how you collected 25k situations? just built by human‘s imagination？
I think it is a big work to build data by self.

**Comment by EricMichaelSmith** [comment]
We crowdsourced the writing of these situations: each participant chose an emotion label, and we had them describe a situation that was associated with that emotion. There were 810 different participants who wrote these situations and conversations. Hope that helps!

**Comment by lsy641** [comment]
Thanks.

**Comment by EricMichaelSmith** [comment]
Sure thing!
