### ISSUE TITLE
Issue with BertTokenizer

### ISSUE THREAD

**Issue by kiranikram** [facebookresearch/EmpatheticDialogues#24]
Hi, I am getting after running the retrieval command I am getting the error:  
File "/Users/ikram/opt/anaconda3/lib/python3.7/site-packages/pytorch_pretrained_bert/tokenization.py", line 109, in tokenize
    if self.do_basic_tokenize:
AttributeError: 'BertTokenizer' object has no attribute 'do_basic_tokenize'

However I cant locate the file to make requisite changes. What would you advise? Thanks!

**Comment by EricMichaelSmith** [comment]
Hi there! Which version of `pytorch-pretrained-BERT` are you using? I've seen this error before - unfortunately for this I believe you need to use an older version of that package. I've tested this code with `pytorch-pretrained-BERT==0.5.1`

**Comment by kiranikram** [comment]
Thank you, that solved that particular issue!
