### ISSUE TITLE
how do you decide uids of a comment and which will be 6?

### ISSUE THREAD

**Issue by lsy641** [facebookresearch/EmpatheticDialogues#25]
the original name and parent_id of a commemt are all a str like "t1_XXX", and when will it be 6 as a deleted comment?
`        if "bert_tokenizer" in dict_:
            self.using_bert = True
            assert BERT_ID == "bert-base-cased"
            deleted_uid = -1
        else:
            self.using_bert = False
            deleted_uid = 6`

**Comment by EricMichaelSmith** [comment]
From my memory, it'll be 6 if the user themselves was removed from the dataset.
