### ISSUE TITLE
about details of dataset

### ISSUE THREAD

**Issue by A-Rain** [facebookresearch/EmpatheticDialogues#35]
Hi, I'm confused about the dataset since there is no readme file. I found the column names are the following:

conv_id | utterance_idx | context | prompt | speaker_idx | utterance | selfeval | tags

does 'context' means the sentiment of each utterence ? And what do 'prompt', 'selfeval' and 'tags' mean ? 

thanks,

**Comment by EricMichaelSmith** [comment]
Hi! Sorry for the delay in responding. "context" is the sentiment of the conversation overall, and "prompt" is the prompt with which the Speaker wrote the first sentence (i.e. it's what the conversation should be about). "selfeval" was human ratings of these conversation utterances (see other Issues in this repo for what they mean), and "tags" represents whether the sentences are rated as political, among other things. (I didn't collect "selfeval" or "tags" and they're not used in the paper, so I'm not aware of all of the subtleties of them.)

**Comment by A-Rain** [comment]
I get it. Thank you for the reply
