### ISSUE TITLE
reddit data

### ISSUE THREAD

**Issue by WilliamsToTo** [facebookresearch/EmpatheticDialogues#36]
Where should I download reddit data?

**Comment by EricMichaelSmith** [comment]
Hi! Unfortunately we can't provide access to the Reddit data - it was from a third-party dump of 1.7 billion Reddit conversations.

**Comment by 17521121** [comment]
https://affect.media.mit.edu/neural_chat/datasets/
You can have a look for this link above, but I am not sure you will need it, because we should do a pretrain not scratch
