### ISSUE TITLE
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

### ISSUE THREAD

**Issue by nizish** [facebookresearch/EmpatheticDialogues#46]
In google colab this command raises exception.

```
!python retrieval_train.py --batch-size 32 --bert-dim 300 --cuda --dataset-name empchat --dict-max-words 250000 --display-iter 100 --embeddings None --empchat-folder ./empatheticdialogues/ --max-hist-len 4 --model bert --model-dir ./test1 --model-name model --optimizer adamax --pretrained bert_finetuned_emoprepend1.mdl --reactonly

Traceback (most recent call last):
  File "retrieval_train.py", line 297, in <module>
    main(opt)
  File "retrieval_train.py", line 254, in main
    net, dictionary = load_model(opt_.pretrained, opt_)
  File "/content/EmpatheticDialogues/empchat/models.py", line 74, in load
    net = create(saved_opt, word_dict["words"])
  File "/content/EmpatheticDialogues/empchat/models.py", line 81, in create
    return BertAdapter(opt, dict_words)
  File "/content/EmpatheticDialogues/empchat/bert_local.py", line 61, in __init__
    embeddings.weight[token_idx] = rand_embedding
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.

```
Found fix at https://stackoverflow.com/questions/49161652/how-to-get-around-in-place-operation-error-if-index-leaf-variable-for-gradient-u

Notebook is here [gist](https://gist.github.com/nizish/8c49b82462f35d6e270d9e22f9bc251a)

**Comment by EricMichaelSmith** [comment]
hmm which version of PyTorch are you using? I wonder if this is version-dependent - the [README ](https://github.com/facebookresearch/EmpatheticDialogues/blob/main/README.md) states that the code uses PyTorch 1.0.1.post2

**Comment by nizish** [comment]
torch                         1.10.0+cu111

**Comment by EricMichaelSmith** [comment]
Hmm, yeah, I'm guessing it's a version-dependent thing. If you're able to get this code to run on modern PyTorch, I'd welcome a PR :)

**Comment by ramish987** [comment]
hello, I have issue in loading these model files in parlai.When i have to load these models to parlai it shows errors to read mdl file docreadertagent is used in some codes but this is used in old versions
Please can you help me with it

**Comment by ramish987** [comment]
I run the code given belowthe models with retrival file in  the end it save .txt model file how can we load it to parlai chatbot

**Comment by EricMichaelSmith** [comment]
Hi @ramish987 ! Unfortunately these model files cannot be loaded natively in ParlAI without mapping the weights into a ParlAI-friendly format, since it was not trained in ParlAI.

**Comment by ramish987** [comment]
So what I have to do for that I have tried to load the code you have given
below in the link but it save txt file .So what I should do? what you
suggest?

**Comment by EricMichaelSmith** [comment]
@ramish987 Is your goal to load the retrieval model in ParlAI? If so, I'd take a look at `parlai/core/torch_ranker_agent.py` to see how weights there map onto the ones in the model in this repo in order to get this model to work in ParlAI.

**Comment by ramish987** [comment]
thanks
