### ISSUE TITLE
Download pretrained models?

### ISSUE THREAD

**Issue by GraphGrailAi** [facebookresearch/EmpatheticDialogues#5]
Can we download pretrained models to use them for inference? 
(Also what is time-to-response for this?) 
As i see in paper, it takes 2-3 days to train myself

**Comment by EricMichaelSmith** [comment]
Unfortunately, we're not able to release pretrained models for this purpose. Hmm - what kind of time-to-response are you concerned with? Yeah, pretraining took us a few days and fine-tuning took around an hour.

**Comment by GraphGrailAi** [comment]
time-to-response - is time to process one sentence to get result with angry or happy class.
Also, what is the final size of model?

**Comment by EricMichaelSmith** [comment]
For the 4-layer retrieval Transformer model, I measure typical forward-pass times of 0.1 sec (for a batch size of 512) and a model size of ~350 MB.
