### ISSUE TITLE
The Reddit Dataset

### ISSUE THREAD

**Issue by yuboxie** [facebookresearch/EmpatheticDialogues#9]
Hi! Is there a way to obtain the 1.7B Reddit dataset? Thanks!

Best,
Yubo

**Comment by EricMichaelSmith** [comment]
Hi! Reddit dumps are available online at various places, which you can find at https://www.reddit.com/r/datasets/comments/3bxlg7/i_have_every_publicly_available_reddit_comment/ or by searching for "reddit dump", etc.

**Comment by yuboxie** [comment]
Thanks! This is really helpful :)
